# Generated by Django 6.0.6 on 2026-06-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenderOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Kompaniya nomi"),
                ),
                ("company_inn", models.CharField(max_length=20, verbose_name="INN")),
                (
                    "company_activity",
                    models.TextField(verbose_name="Kompaniya faoliyati"),
                ),
                ("company_experience", models.TextField(verbose_name="Tajriba")),
                ("tender_url", models.URLField(verbose_name="Tender linki")),
                (
                    "tender_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Tender nomi"
                    ),
                ),
                (
                    "tender_description",
                    models.TextField(blank=True, verbose_name="Tender tavsifi"),
                ),
                (
                    "price_offer",
                    models.CharField(max_length=255, verbose_name="Narx taklifi"),
                ),
                (
                    "generated_document",
                    models.TextField(blank=True, verbose_name="AI yozgan hujjat"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("processing", "Ishlanmoqda"),
                            ("done", "Tayyor"),
                            ("error", "Xatolik"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tender buyurtma",
                "verbose_name_plural": "Tender buyurtmalar",
            },
        ),
    ]
